# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: csc5201-lab-8
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: csc5201-lab-8
  type: LoadBalancer
